## try-catch-finally
try-catch 기본 형식은 코틀린 자바 모두 동일.  
다만 다른점이 있다면, ```catch```문에서 타입과 변수명 위치와 ```new```키워드를 안쓴다는것.  

```java
//java
int parseIntToThrow(@NotNull String str) {
    try {
        return Integer.parseInt(str);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException(String.format("주어진 %s는 숫자가 아닙니다.", str));
    }
}
```
```kotlin
//kotlin
fun parseIntToThrow(str:String) : Int {
    try {
        return str.toInt();
    } catch (e : NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.")
    }
}
```
기본형식은 같지만 코틀린에서는 try-catch또한 Expression이기 때문에 아래처럼  
바로 리턴할 수 있다!!
```kotlin
fun parseIntToThrow2(str:String) : Int? {
    return try {
        str.toInt();
    } catch (e : NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.");
        // OR 값리턴도 가능.
    }
}
```
---
## Checked Exception / UnChecked Exception
자바는 Checked / Unchecked Ex가 나눠지지만, **코틀린은 모두 Unchecked Ex만 존재하며,  
자바에서 Checked Ex로 취급하는 Ex또한 모두 Unchecked Ex로 취급 된다.**

```java
//java
void readFile() throws IOException { //throws를 안붙히면 컴파일 에러.
    File currentFile = new File(".");
    File file = new File(currentFile.getAbsolutePath() + "/a.txt");
    BufferedReader reader = new BufferedReader(new FileReader(file));
    System.out.println(reader.readLine());
    reader.close();
}
```
```kotlin
    fun readFile() { //kotlin은 붙히지 않아도, 빨간줄이 발생하지 않는다!!
        val currentFile = File(".");
        val file = File(currentFile.absolutePath + "/a.txt");
        val reader = BufferedReader(FileReader(file));
        println(reader.readLine())
        reader.close()

    }

```
---
## try-with-resources
코틀린에서는 try-with-resources을 사용할 수 없다. 하지만 아래와 같이 코틀린 확장함수인 ```use()``` 함수를 통해  
자바의 try-with-resources와 동일하게 동작하게 작성할 수 있다.
```java
//java
void readFile(String path) throws IOException {
    try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
        System.out.println(reader.readLine());
    }
}
```
```kotlin
//kotlin

```